### ISSUE TITLE
with-editor: TODO

### ISSUE THREAD

**Issue by Silex** [magit/git-modes#113]
Hello,

Instead of creating thousands of tickets, and to keep track of all of what was said, here is a list of the things that are still pending:
- [x] investigate ansi-colors disappearing _(doesn't happen anymore)_
- [x] whether we care about the fact that the variable `eshell-preoutput-filter-functions` is permanently changed once we use with-editor in eshell.
- [x] whether we really need to call `(with-editor-mode 1)` from `git-commit-mode` (https://github.com/magit/git-modes/commit/9fe62b140f2fe44328d12740c2705671409187a3) _(yes)_
- [x] term: how to execute "invisible" commands
- [x] shell: how to execute "invisible" commands
- [x] eshell: how to execute "invisible" commands
- [x] whether the check against `file-name-absolute-p` is really necessary in `with-editor-output-filter` (https://github.com/magit/git-modes/commit/e84cb723f2ab57232b911406c8d13facbfe5c25d)
- [ ] whether we should use `file-remote-p` or `tramp-tramp-file-p` (https://github.com/magit/git-modes/pull/96)
- [x] whether we should add `with-editor-export-hg-editor` (https://github.com/magit/git-modes/commit/a6d43981db6cb4fdc40756b6e23684a9a074fa2e)
- [x] ~~or whether we should remove `with-editor-export-git-editor`~~
- [x] compile a list of "override `$EDITOR` variables" in common use.
- [x] ~~whether we should just add `with-editor-mode` to `server-visit-hook` and be done with it~~
- [x] ~~or whether we should instead implement `global-with-editor-mode` and `(global-) shell-with-editor-mode`, and sprinkle conditionals all over the code.~~

---

Related discussions: #91, #92, #96, #102, #108, #112, #116
